
spring:
  datasource:

    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 712459
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

